---
title: "DESeq analysis"
author: "Joseph J Zhao"
date: "4/12/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "devtools", "stringr", "stringi", "gtools",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2", "BiocParallel", "clusterProfiler",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines", "Hmisc", "rms",
  # misc
  "cluster", "ResourceSelection", "digitize",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE)} else {library(package.name, character.only = TRUE)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}

```

## Set main working directory

```{r working directory}
wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

Create storage list

```{r}

l_rna=list(); l_rna_norm=list(); l_ref=list()

```

Prepare data

```{r}

path="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/submissions/substudies/crcpm/submissions/ccr/r1/workings"

l_gipm_rnaseq <- readRDS(paste0(path,"/data/wts/l_crc_rnaseq.rds"))

df_rna=l_gipm_rnaseq$gene_count
df_rna_norm=l_gipm_rnaseq$gene_log2fpkm

df_ref <- read_excel(paste0(path,"/data/reference/df_ref_pm_persample_annotated_crc.xlsx"))

df_ref=subset(df_ref, df_ref$rnaseq==1 & df_ref$rnaseqid %in% colnames(df_rna_norm) & df_ref$gccrc=="crc")

df_rna_norm=df_rna_norm[, colnames(df_rna_norm) %in% df_ref$rnaseqid]
df_rna=df_rna[, colnames(df_rna) %in% df_ref$rnaseqid]
df_rna=df_rna[!apply(df_rna, 1, sum)==0, ]
df_rna=df_rna[!apply(df_rna, 1, function(x){any(x>1000000000)}),] # exclude outliers

l_rna[["crc"]]=df_rna
l_rna_norm[["crc"]]=df_rna_norm
l_ref[["crc"]]=df_ref

```

### labelling

# Run Deseq

```{r}

l_de=list()

cat="sampletype"

for (i.gccrc in "crc"){
  for(i.cat in cat){
    # identify unique groups
    groups=unique(as.vector(unlist(df_ref[df_ref$gccrc==i.gccrc,i.cat])))
    
    # overwrite - order it such that comparisons are standardized
    groups=c("peritonealtumor", "primarytumor", "peritonealnormal", "primarynormal")
    
    combs=combinations(length(groups), 2) # create matrix of possible combinations
  
    for(i.combs in 1:nrow(combs)){
      tryCatch({
      id.1=(df_ref[df_ref[,i.cat]==groups[combs[i.combs,1]],]$rnaseqid) # IDs of group 1
      id.2=(df_ref[df_ref[,i.cat]==groups[combs[i.combs,2]],]$rnaseqid) # IDs of group 2
      
      df_ref_temp=df_ref[df_ref$rnaseqid %in% c(id.1, id.2),]
      df_ref_temp$cat=as.vector(unlist(df_ref_temp[,i.cat]))
      df_ref_temp$cat=factor(df_ref_temp$cat, levels = c(groups[combs[i.combs,2]], groups[combs[i.combs,1]])) # to ensure that the comparison direction is the same
      df_ref_temp=df_ref_temp[order(df_ref_temp$cat), ]
      
      df_ref_temp=df_ref_temp[match(colnames(df_rna[,c(id.1, id.2)]), df_ref_temp$rnaseqid),]

      # run deseq after truncating dataset
      dds=DESeqDataSetFromMatrix(countData = df_rna[, colnames(df_rna) %in% c(id.1, id.2)],  
                                                colData = df_ref_temp,
                                                design = ~ cat)
      
      featureData <- data.frame(gene=rownames(df_rna))
      mcols(dds) <- DataFrame(mcols(dds), featureData)
      
      dds <- DESeq(dds, parallel=TRUE, BPPARAM=MulticoreParam(20))
      res <- results(dds)
      l_de[[paste0(groups[combs[i.combs,1]], " vs ", groups[combs[i.combs,2]])]]=res
      }, 
      error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
    }
  }
}

```

## Save l_de; read l_de

```{r}

saveRDS(l_de, file=paste0(path, "/data/rnaseq_collated/l_de_ptpm_crc.rds"))

```


