---
title: "CRCPM PTPM immunedecon"
author: "Joseph J Zhao"
date: "11/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "stringr", "stringi", "gtools",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2","preprocessCore", "umap", "DGEobj.utils", "edgeR", "sva", "GSVA", "GSEABase", "DGEobj.utils", "msigdbr", "immunedeconv",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines",
  # misc
  "cluster", "ResourceSelection", "digitize", "statip", "dad",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid", "ggbiplot", "ggsankey", "RColorBrewer"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE)} else {library(package.name, character.only = TRUE)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


```

## Set main working directory

```{r working directory}
wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

# Load count data and clinical data of combined gascad and peritoneal data     

```{r}

path="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/submissions/substudies/crcpm/submissions/ccr/r1/workings"

# reference sheets
df_ref_pm_persample <- read_excel(paste0(path,"/data/reference/df_ref_pm_persample_annotated_crc.xlsx"))
# df_ref_pm_persample <- read_excel(paste0(path,"/data/reference/df_ref_pm_perpatient_crc.xlsx"))

# rnaseq
l_rnaseq <- readRDS(paste0(path,"/data/wts/l_crc_rnaseq.rds"))

df_ref=subset(df_ref_pm_persample, df_ref_pm_persample$rnaseqid %in% colnames(l_rnaseq$gene_log2fpkm))

df_ref$sampletype_crc=ifelse(df_ref$sampletype=="peritonealnormal", paste0(df_ref$sampletype, "-", df_ref$gccrc), df_ref$sampletype)

```

# load immune decon
https://icbi-lab.github.io/immunedeconv/articles/detailed_example.html
previously ran with ImmuneDecon wrapper package - retrieved xCell and Cibersort

```{r}

df_immunedeconvo=readRDS(paste0(path,"/data/rnaseq_collated/df_immunedeconvo.rds"))

```


# Run pairwise comparisons with t test
- using T test to compare

```{r}
# prepare holders to store data
df_immunedeconvo_t=NULL
l_immunedeconvo_t=list()

cat="sampletype_crc" # define the categories we will be splitting the dataset by

for(i.cat in cat){
  # identify unique groups
  groups=unique(as.vector(unlist(df_ref[,i.cat]))) # for now remove the adjacent peritonuem
  
  groups=c("peritonealtumor", "primarytumor",  "peritonealnormal-crc", "primarynormal", "peritonealnormal-benign")
  
  combs=combinations(length(groups), 2) # create matrix of possible combinations

for(i.combs in 1:nrow(combs)){
    id.1=(df_ref[df_ref[,i.cat]==groups[combs[i.combs,1]],])$rnaseqid # IDs of group 1
    id.2=(df_ref[df_ref[,i.cat]==groups[combs[i.combs,2]],])$rnaseqid # IDs of group 2
  
    # run t test to compare the cell proportions between upper and lower
    no_cores <- 8
    registerDoParallel(makeCluster(no_cores))
    
    out=foreach(i.cell = 1:length(df_immunedeconvo$cell_type), .combine=rbind) %dopar% {
        
        ttest=t.test(df_immunedeconvo[i.cell,id.1],
                     df_immunedeconvo[i.cell,id.2])
        
        c(comparison=paste0(groups[combs[i.combs,1]], " vs " ,groups[combs[i.combs,2]]), 
          cell_type=df_immunedeconvo$cell_type[i.cell], 
          method=df_immunedeconvo$var_method[i.cell], ttest$statistic, p.value=ttest$p.value)
        
    }
    
    stopImplicitCluster()
    
    df_immunedeconvo_t=rbind(df_immunedeconvo_t, out)
  
  # cleaning
  df_immunedeconvo_t=data.frame(df_immunedeconvo_t)
  rownames(df_immunedeconvo_t)=NULL
  df_immunedeconvo_t[, c(3:ncol(df_immunedeconvo_t))]=apply(df_immunedeconvo_t[, c(3:ncol(df_immunedeconvo_t))], 2, as.numeric)
  # reorder
  df_immunedeconvo_t$cell_type=factor((df_immunedeconvo_t$cell_type), levels=unique(df_immunedeconvo_t[order(df_immunedeconvo_t$t),]$cell_type))

  l_immunedeconvo_t[[paste0(groups[combs[i.combs,1]], " vs " ,groups[combs[i.combs,2]])]]=df_immunedeconvo_t
  
  df_immunedeconvo_t=NULL
  
  }
  
}

lapply(l_immunedeconvo_t, head)

```

## Visualization for comparisons
Dot plot

```{r}

pdf(paste(Sys.Date(),paste0("immunedeconvo_allmethods_dotplot.pdf")), height=3.25, width=5)
for (i.comb in names(l_immunedeconvo_t)[1]){
  plot_immunedeconvo_dotplot=ggplot()+
                                geom_point(aes(x=t, y=cell_type, alpha=p.value<0.05, color=t<0), data=subset(l_immunedeconvo_t[[i.comb]], !is.na(l_immunedeconvo_t[[i.comb]]$p.value) & abs(l_immunedeconvo_t[[i.comb]]$t)>1.75 &!grepl("score", l_immunedeconvo_t[[i.comb]]$cell_type)), size=3, stroke=NA)+
                                scale_color_brewer(palette="Dark2")+                            
                                scale_color_manual(values=c("firebrick3", "dodgerblue3"))+
                                labs(title=paste0(""), y="", x=paste0(str_extract(i.comb, "(?<= vs ).*"),"   |   ", str_extract(i.comb, ".*(?= vs )"),"\nt-statistic"), alpha="p<0.05") +
                                guides(alpha="none", color="none")+
                                geom_vline(xintercept=0, col="black")
  
  plot_immunedeconvo_dotplot %>% print
}
dev.off()

```
