---
title: "A5 WTS prep"
author: "Joseph J Zhao"
date: "11/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "stringr", "stringi", "gtools", "maditr", "reshape2",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2","preprocessCore", "umap", "DGEobj.utils", "edgeR", "sva",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines",
  # misc
  "cluster", "ResourceSelection", "digitize", "statip", "dad",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid", "ggbiplot", "ggsankey"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE, quietly = T)} else {library(package.name, character.only = TRUE, quietly = T)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


```

## Set main working directory

```{r working directory}
wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

## load data

```{r}

# raw count
df_rna_1=read_excel("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/wts/rep1/data2.xlsx")
df_rna_2=read_excel("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/wts/rep2/data2.xlsx")
df_rna_1=subset(df_rna_1, select=c("Gene_Symbol", "PC383IgGr1_Read_Count", "PC383A5r1_Read_Count"))
df_rna_2=subset(df_rna_2, select=c("Gene_Symbol", "PC383IgGr2_Read_Count", "PC383A5r2_Read_Count"))

df_rna_count=left_join(df_rna_1, df_rna_2, by="Gene_Symbol") %>% as.data.frame()
rownames(df_rna_count)=df_rna_count$Gene_Symbol; df_rna_count$Gene_Symbol=NULL
colnames(df_rna_count)=str_replace_all(colnames(df_rna_count), "_Read_Count", "")

# log2fpkm
df_rna_log2fkpm=left_join(read.delim("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/wts/rep1/norm.count.txt")[,-1], 
          read.delim("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/wts/rep2/norm.count.txt")[,-1], by="Gene_Symbol") %>% as.data.frame()

rownames(df_rna_log2fkpm)=df_rna_log2fkpm$Gene_Symbol; df_rna_log2fkpm$Gene_Symbol=NULL

# reference
df_rna_ref=data.frame(rnaseqid=colnames(df_rna_log2fkpm), treatment=str_extract(colnames(df_rna_log2fkpm), "IgG|A5"))

# collate

l_a5_wts=list(
  df_rna_count=df_rna_count,
  df_rna_log2fkpm=df_rna_log2fkpm,
  df_rna_ref=df_rna_ref
)


saveRDS(l_a5_wts, "C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/wts/l_a5_wts.rds")

```
