---
title: "Lunaphore overview - for t cell subgroups"
author: "Joseph J Zhao"
date: "11/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "stringr", "stringi", "gtools", "maditr", "reshape2",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2","preprocessCore", "umap", "DGEobj.utils", "edgeR", "sva", "sf", "RANN", "spatstat",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines",
  # misc
  "cluster", "ResourceSelection", "digitize", "statip", "dad",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid", "ggbiplot", "ggsankey", "ggVennDiagram"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE, quietly = T)} else {library(package.name, character.only = TRUE, quietly = T)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


```

## Set main working directory

```{r working directory}
wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

import

```{r}

path="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/submissions/substudies/crcpm/submissions/ccr/r1/workings"

l_lunaphore_crcpm=readRDS(paste0(path,"/data/lunaphore/l_lunaphore_crcpm_tcellsubsets.rds"))

```

overview numbers

```{r}

# number of ROI
l_lunaphore_crcpm$df_ref_percell$roiid %>% unique %>% length

# number of slides
unique(l_lunaphore_crcpm$df_ref_percell$lunaphoreid )

# number of cells
l_lunaphore_crcpm$df_ref_percell$cellid %>% unique %>% length

# number of patients
l_lunaphore_crcpm$df_ref_percell$patientid %>% unique %>% length

# cells per PTPM
table(l_lunaphore_crcpm$df_ref_percell$primarypm)

# slideser ptpm
table(l_lunaphore_crcpm$df_ref_perroi$lunaphoreid, l_lunaphore_crcpm$df_ref_perroi$primarypm)

# per roitype
table(l_lunaphore_crcpm$df_ref_percell$primarypm, l_lunaphore_crcpm$df_ref_percell$roi_type)


```


PT PM cell type counts and proportions

```{r}

df_celltypeprop=data.frame()

for (i.roi_type in unique(l_lunaphore_crcpm$df_ref_percell$roi_type)){
  df_temp=subset(l_lunaphore_crcpm$df_ref_percell, l_lunaphore_crcpm$df_ref_percell$roi_type==i.roi_type)
  
  m=as.data.frame.matrix(table(df_temp$primarypm, df_temp$celltype))
  m %>% chisq.test() %>% print
  
  m$primarypm=rownames(m)
  m$roi_type=i.roi_type
  
  df_celltypeprop=bind_rows(df_celltypeprop, m)
  
}

df_celltypeprop[, 1:(ncol(df_celltypeprop)-2)]=t(apply(df_celltypeprop[, 1:(ncol(df_celltypeprop)-2)], 1, function(x){x/sum(x)}))
rownames(df_celltypeprop)=NULL; df_celltypeprop$roi_type[df_celltypeprop$roi_type=="Tumor_boundary"]="TSI"

df_celltypeprop_melt=melt(df_celltypeprop)
df_celltypeprop_melt$primarypm=factor(df_celltypeprop_melt$primarypm, levels=c("primary", "peritoneal"))

n_cells=nrow(subset(l_lunaphore_crcpm$df_ref_percell, grepl("T ", l_lunaphore_crcpm$df_ref_percell$celltype)))

plot_stackbarchartcelloverview=ggplot(aes(y=value, x=primarypm, fill=variable), data=df_celltypeprop_melt) +
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~roi_type) +
  labs(y="Proportion of cells", x="", fill=paste0("n=", formatC(n_cells, format="d", big.mark=","))) +
  scale_fill_manual(values=c(RColorBrewer::brewer.pal(5, "Set1")))

pdf(paste(Sys.Date(),paste0("_lunaphore_plot_stackbarchartcelloverview_tcells.pdf")), height=3.25, width=6.5)
print(plot_stackbarchartcelloverview)
dev.off()


```

