---
title: "A5 figures"
author: "Joseph J Zhao"
date: "11/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "stringr", "stringi", "gtools", "maditr", "reshape2",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2","preprocessCore", "umap", "DGEobj.utils", "edgeR", "sva",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines",
  # misc
  "cluster", "ResourceSelection", "digitize", "statip", "dad",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid", "ggbiplot", "ggsankey"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE, quietly = T)} else {library(package.name, character.only = TRUE, quietly = T)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


```

## Set main working directory

```{r working directory}
wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

## load data

```{r}

df_tpaupa<- read_excel("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/c.A5 - Biochemical - tPA/20210528 tPA hAb 1ug trplicates_Results - clean.xlsx")
df_prolif=Antibody_proliferation_Results <- read_excel("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/f.A5 - in vitro Proliferation/Antibody proliferation_Results.xlsx")
df_stat3=read_excel("C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/data/crcpm_a5data/g.A5 pSTAT3/pSTAT3_A5_Results.xlsx")

```

## plot tpaupa

```{r}

pa=grep("perc", colnames(df_tpaupa), value=T)

pdf(paste(Sys.Date(),paste0("_tpaupa_barchart.pdf")), height=2, width=2.3)

for (i.pa in pa){
  
  df_tpaupa$value=df_tpaupa[, i.pa] %>% unlist %>% as.vector 
  df_tpaupa_temp=subset(df_tpaupa, select=c("treatment", "value"))
  
  t=t.test(value~treatment, df_tpaupa_temp)
  
  df_tpaupa_mean=aggregate(value~treatment, df_tpaupa_temp, mean); colnames(df_tpaupa_mean)[2]="mean"
  df_tpaupa_sd=aggregate(value~treatment, df_tpaupa, sd); colnames(df_tpaupa_sd)[2]="sd"
  df_tpaupa_temp=left_join(df_tpaupa_mean, df_tpaupa_sd, by="treatment")
  df_tpaupa_temp$treatment=factor(df_tpaupa_temp$treatment, levels=c("IgG", "A5"))
  
  
  p=ifelse(t$p.value<0.001, formatC(t$p.value, format = "e", digits = 2), format(round(t$p.value, 3), nsmall=3))

  plot_pa=ggplot() +
    # theme_classic() +
    geom_bar( aes(x=treatment, y=mean, fill=treatment), stat="identity", alpha=0.9, data=df_tpaupa_temp, width=0.6, color="black")  +
    geom_errorbar(aes(x=treatment, y=mean, ymin=mean-sd, ymax=mean+sd), width=0.5, colour="black", alpha=0.9, size=0.5, data=df_tpaupa_temp) +
    labs(x="", y="PAI-1 activity (%)", title=str_replace_all(i.pa, "_perc", "")) +
    scale_fill_manual(values=c("grey", "orange3")) +
    guides(fill="none") +
    annotate("text", y=90, x=2, label=paste0("p = ", p))
  
  print(plot_pa)
  
}

dev.off()


```

## plot antibody proliferation

```{r}

df_prolif$cellline=str_replace_all(df_prolif$cellline, "_", "")
df_prolif$treatment_cellline=paste0(df_prolif$treatment,  "_", df_prolif$cellline)

comps=compare_means(viability~treatment_cellline, data=df_prolif, method="t.test")
comps$treatment1=str_split(comps$group1, "_", simplify = T)[,1]
comps$treatment2=str_split(comps$group2, "_", simplify = T)[,1]

comps$cellline1=str_split(comps$group1, "_", simplify = T)[,2]
comps$cellline2=str_split(comps$group2, "_", simplify = T)[,2]

comps=subset(comps, !comps$treatment1==comps$treatment2 & comps$cellline1==comps$cellline2 & !comps$cellline1=="FBS")

df_prolif_mean=aggregate(viability~treatment + cellline, df_prolif, mean)
colnames(df_prolif_mean)[3]="mean"

df_prolif_sd=aggregate(viability~treatment + cellline, df_prolif, sd)
colnames(df_prolif_sd)[3]="sd"

df_prolif_temp=left_join(df_prolif_mean, df_prolif_sd, by=c("treatment", "cellline"))
df_prolif_temp$treatment=factor(df_prolif_temp$treatment, levels=c("IgG", "A5"))

# p=ifelse(t$p.value<0.001, formatC(t$p.value, format = "e", digits = 2), format(round(t$p.value, 3), nsmall=3))

plot_prolif=ggplot(aes(x=cellline, y=mean, fill=treatment), data=subset(df_prolif_temp, !df_prolif_temp$cellline=="FBS")) +
  geom_bar( stat="identity", position=position_dodge(), alpha=0.9, width=0.85, color="black") +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), position=position_dodge(1), width=0.5, alpha=0.9, size=0.5) +
  labs(x="", y="Cell viability (%)\nat 150 μg/mL biologics", title="") +
  scale_fill_manual(values=c("grey", "orange3")) +
  guides(fill="none") +
  coord_flip(ylim=c(0,130)) +
  annotate("text", y=120, x=comps$cellline1, label=paste0("p = ", comps$p.format), size=3.35)

pdf(paste(Sys.Date(),paste0("_prolif_barchart.pdf")), height=4, width=5.5)
print(plot_prolif)
dev.off()

```


## stat3

```{r}

df_stat3$cellline=str_replace_all(df_stat3$cellline, "_", "")
df_stat3$treatment_conc=paste0(df_stat3$treatment,  "_", df_stat3$conc)

comps=compare_means(viability~treatment_conc, data=df_stat3, method="t.test")
comps$treatment1=str_split(comps$group1, "_", simplify = T)[,1]
comps$treatment2=str_split(comps$group2, "_", simplify = T)[,1]

comps$conc1=str_split(comps$group1, "_", simplify = T)[,2]
comps$conc2=str_split(comps$group2, "_", simplify = T)[,2]

comps=subset(comps, !comps$treatment1==comps$treatment2 & comps$conc1==comps$conc2)

df_stat3_mean=aggregate(viability~treatment + conc, df_stat3, mean)
colnames(df_stat3_mean)[3]="mean"

df_stat3_sd=aggregate(viability~treatment + conc, df_stat3, sd)
colnames(df_stat3_sd)[3]="sd"

df_stat3_temp=left_join(df_stat3_mean, df_stat3_sd, by=c("treatment", "conc"))
df_stat3_temp$treatment=factor(df_stat3_temp$treatment, levels=c("IgG", "A5"))
df_stat3_temp$conc=factor(df_stat3_temp$conc, levels=unique(df_stat3_temp$conc))

plot_prolif=ggplot(aes(x=conc, y=mean, fill=treatment), data=df_stat3_temp) +
  geom_bar( stat="identity", position=position_dodge(), alpha=0.9, width=0.85, color="black") +
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), position=position_dodge(1), width=0.5, alpha=0.9, size=0.5) +
  labs(x="Concentration, μg/mL", y="pSTAT3/STAT3 relative to PBS control (%)", title="", fill="") +
  scale_fill_manual(values=c("grey", "orange3")) +
  # guides(fill="none") +
  coord_flip(ylim=c(0,140)) +
  annotate("text", y=130, x=comps$conc1, label=paste0("p = ", comps$p.format), size=3.35)

pdf(paste(Sys.Date(),paste0("_stat3_barchart.pdf")), height=4, width=6)
print(plot_prolif)
dev.off()

```


