---
title: "CRC cohort fig"
author: "Joseph J Zhao"
date: "11/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
package.name=c(
  # data manipulation
  "tidyverse", "readr", "readxl", "dplyr", "tidyr", "lubridate", "tibble", "plyr", "stringr", "stringi", "gtools", "maditr", "reshape2",
  # parallel processing
  "doParallel", "parallel", "foreach",
  # bioinformatics
  "DESeq2","preprocessCore", "umap", "DGEobj.utils", "edgeR", "sva",
  # survival analysis
  "survminer", "survival", "rstpm2", "survRM2",
  # regression stuff
  "MASS", "splines",
  # misc
  "cluster", "ResourceSelection", "digitize", "statip", "dad", "tableone",
  # plotting
  "blandr", "pheatmap", "ggrepel", "ggplot2", "corrplot", "ggpubr", "gplots", "grid", "ggbiplot", "ggsankey"
)

for (package.name in package.name){
  tryCatch(
  {
  if (!require(package.name, character.only = TRUE)){ 
    install.packages(package.name, character.only = TRUE) 
    library(package.name, character.only = TRUE, quietly = T)} else {library(package.name, character.only = TRUE, quietly = T)}
  }, 
    error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
}


```

## Set main working directory

```{r working directory}

wd="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/"
setwd(wd)

dir.create(paste(wd,"output/", Sys.Date(), sep=""))
setwd(paste(wd, "output/",Sys.Date(), sep="") )

```

## Load data

```{r}

path="C:/Users/jzhao/OneDrive/Research_Cloud/NUH_NCIS/gccrc_pm/submissions/substudies/crcpm/submissions/ccr/r1/workings"

df_ref_pm_perpatient <- read_excel(paste0(path,"/data/reference/df_ref_pm_perpatient_crc.xlsx"))
df_ref_pm_persample <- read_excel(paste0(path,"/data/reference/df_ref_pm_persample_annotated_crc.xlsx"))

l_rnaseq <- readRDS(paste0(path,"/data/wts/l_crc_rnaseq.rds"))
dsp_crc <- readRDS(paste0(path,"/data/dsp/dsp_crc.rds"))
l_gipm_wes <- readRDS(paste0(path,"/data/wes/l_gipm_wes.rds"))
l_lunaphore_crcpm <- readRDS(paste0(path,"/data/lunaphore/l_lunaphore_crcpm.rds"))

```

### sync up the persample and perpatient sheet

```{r}

df_ref_pm_persample=subset(df_ref_pm_persample, (df_ref_pm_persample$rnaseq==1 | df_ref_pm_persample$wesid==1 | df_ref_pm_persample$dsp==1 | df_ref_pm_persample$lunaphore==1) & 
                             !df_ref_pm_persample$primarypm=="UNK" & 
                             !df_ref_pm_persample$tumornormal=="UNK" &
                             df_ref_pm_persample$gccrc== "crc" &
                             (df_ref_pm_persample$rnaseqid %in% colnames(l_rnaseq$gene_log2fpkm) |
                                df_ref_pm_persample$wesid %in% unique(l_gipm_wes$wes_all$Sample) |  
                                df_ref_pm_persample$lunaphoreid %in% unique(l_lunaphore_crcpm$df_ref_percell$lunaphoreid) |
                                df_ref_pm_persample$dspid %in% colnames(dsp_crc@assayData$q_norm)))

df_ref_pm_perpatient=subset(df_ref_pm_perpatient, df_ref_pm_perpatient$patientid %in% df_ref_pm_persample$patientid & df_ref_pm_perpatient$tumor_gccrc=="crc")
df_ref_pm_persample=subset(df_ref_pm_persample, df_ref_pm_persample$patientid %in% df_ref_pm_perpatient$patientid)

seqtype=c("rnaseq", "wes", "dsp")
for(i.seqtype in seqtype){df_ref_pm_persample[,i.seqtype]=ifelse(df_ref_pm_persample[,i.seqtype]==1, i.seqtype, NA)}

df_ref_pm_persample$sampletype=paste0(df_ref_pm_persample$primarypm, "-", df_ref_pm_persample$tumornormal)

```

## cohort table

```{r}

df_ref_cohortable=subset(df_ref_pm_perpatient, select=c("demo_age", "demo_gender", "demo_race", "demo_ecog", "tumor_tstage", "tumor_nstage", "pm_pciscore1"))

df_ref_cohortable$demo_ecog=as.character(df_ref_cohortable$demo_ecog)

cohortab=CreateTableOne(data=df_ref_cohortable)
cohortab_print=print(cohortab, nonnormal = c("demo_age", "pm_pciscore1"))

write.csv(cohortab_print, "crcpm_cohortab.csv")

```










